from .catalog import CatalogResource
from .chart import ChartResource
from .checklist import ChecklistResource
from .dialect import DialectResource
from .file import FileResource
from .inquiry import InquiryResource
from .json import JsonResource
from .metadata import MetadataResource
from .package import PackageResource
from .pipeline import PipelineResource
from .report import ReportResource
from .resource import ResourceResource
from .schema import SchemaResource
from .table import TableResource
from .text import TextResource
from .view import ViewResource
