module.exports = {
  introduction: ["introduction/introduction", "introduction/whats-next"],
  guides: [
    "guides/guides-overview",
    "guides/quick-start",
    "guides/overview-example",
    "guides/describing-data",
    "guides/extracting-data",
    {
      "Validating Data": [
        "guides/validation-guide",
        "guides/validation-checks",
      ],
    },
    "guides/transforming-data",
    {
      "Mastering the Framework": [
        "guides/package-guide",
        "guides/resource-guide",
        "guides/schema-guide",
        "guides/field-guide",
        "guides/layout-guide",
        "guides/detector-guide",
        "guides/inquiry-guide",
        "guides/report-guide",
        "guides/pipeline-guide",
        "guides/status-guide",
      ],
      "Writing an Extension": [
        "guides/system-guide",
        "guides/plugin-guide",
        "guides/scheme-guide",
        "guides/format-guide",
        "guides/storage-guide",
        "guides/server-guide",
        "guides/error-guide",
        "guides/check-guide",
        "guides/step-guide",
        "guides/type-guide",
      ],
    },
    "guides/whats-next",
  ],
  tutorials: [
    "tutorials/tutorials-overview",
    "tutorials/working-in-python",
    "tutorials/working-with-cli",
    "tutorials/working-with-api",
    {
      "Schemes Tutorials": [
        "tutorials/buffer-tutorial",
        "tutorials/local-tutorial",
        "tutorials/multipart-tutorial",
        "tutorials/remote-tutorial",
        "tutorials/s3-tutorial",
        "tutorials/stream-tutorial",
      ],
      "Formats Tutorials": [
        "tutorials/bigquery-tutorial",
        "tutorials/ckan-tutorial",
        "tutorials/csv-tutorial",
        "tutorials/excel-tutorial",
        "tutorials/gsheets-tutorial",
        "tutorials/html-tutorial",
        "tutorials/inline-tutorial",
        "tutorials/json-tutorial",
        "tutorials/ods-tutorial",
        "tutorials/pandas-tutorial",
        "tutorials/spss-tutorial",
        "tutorials/sql-tutorial",
      ],
    },
    "tutorials/whats-next",
  ],
  references: [
    "references/references-overview",
    "references/plugins-reference",
    "references/schemes-reference",
    "references/formats-reference",
    "references/errors-reference",
    "references/checks-reference",
    "references/steps-reference",
    "references/types-reference",
    "references/api-reference",
    "references/whats-next",
  ],
  development: [
    "development/development",
    "development/changelog",
    "development/migration",
    "development/authors",
    "development/contributing",
    "development/whats-next",
  ],
};
